export const SHEET_NAMES = {
  expertTopics: 'expert_topics',
  storyTopics: 'story_topics',
  creativeIdeas: 'creative_ideas',
  sliderTopics: 'slider_topics',
  contentQueue: 'content_queue',
  promptConfig: 'prompt_templates',
  publishLog: 'publish_log',
  botLogs: 'bot_logs',
  tgSessions: 'tg_sessions',
  workCollections: 'work_collections',
  callbackTokens: 'callback_tokens',
  idempotencyKeys: 'idempotency_keys',
  publishLocks: 'publish_locks',
  jobRuntimeCache: 'job_runtime_cache',
};

export const TABLE_NAMES = SHEET_NAMES;

export const BUSINESS_SHEET_HEADERS = {
  [SHEET_NAMES.expertTopics]: [
    'topic_id',
    'title',
    'brief',
    'tags',
    'priority',
    'status',
    'reserved_by',
    'reserved_at',
    'reservation_expires_at',
    'last_job_id',
    'last_published_at',
    'notes',
  ],
  [SHEET_NAMES.storyTopics]: [
    'topic_id',
    'title',
    'brief',
    'tags',
    'priority',
    'status',
    'reserved_by',
    'reserved_at',
    'reservation_expires_at',
    'last_job_id',
    'last_published_at',
    'notes',
  ],
  [SHEET_NAMES.creativeIdeas]: [
    'topic_id',
    'title',
    'brief',
    'tags',
    'priority',
    'status',
    'reserved_by',
    'reserved_at',
    'reservation_expires_at',
    'last_job_id',
    'last_published_at',
    'notes',
  ],
  [SHEET_NAMES.sliderTopics]: [
    'topic_id',
    'title',
    'brief',
    'tags',
    'priority',
    'status',
    'reserved_by',
    'reserved_at',
    'reservation_expires_at',
    'last_job_id',
    'last_published_at',
    'notes',
  ],
  [SHEET_NAMES.contentQueue]: [
    'queue_id',
    'job_id',
    'job_type',
    'revision',
    'status',
    'scheduled_at',
    'publish_channel',
    'caption_text',
    'collage_drive_file_id',
    'asset_drive_file_ids',
    'topic_id',
    'vk_post_id',
    'publish_attempt_count',
    'last_publish_attempt_at',
    'last_error_code',
    'last_error_message',
    'created_at',
    'updated_at',
  ],
  [SHEET_NAMES.promptConfig]: [
    'prompt_key',
    'version',
    'status',
    'model_id_override',
    'temperature',
    'content',
    'notes',
    'updated_at',
  ],
  [SHEET_NAMES.publishLog]: [
    'publish_id',
    'queue_id',
    'job_id',
    'channel',
    'status',
    'attempt_no',
    'vk_owner_id',
    'vk_post_id',
    'vk_attachment_ids',
    'provider_error_code',
    'provider_error_message',
    'raw_response_ref',
    'created_at',
  ],
  [SHEET_NAMES.botLogs]: [
    'ts',
    'level',
    'event',
    'workflow',
    'execution_id',
    'chat_id',
    'user_id',
    'job_id',
    'queue_id',
    'source_type',
    'stage',
    'collection_id',
    'node',
    'status',
    'duration_ms',
    'message',
    'payload_json',
  ],
};

export const RUNTIME_SHEET_HEADERS = {
  [SHEET_NAMES.tgSessions]: [
    'session_id',
    'chat_id',
    'user_id',
    'mode',
    'state',
    'active_job_id',
    'pending_payload_json',
    'expires_at',
    'updated_at',
  ],
  [SHEET_NAMES.workCollections]: [
    'collection_id',
    'collection_key',
    'chat_id',
    'user_id',
    'first_message_id',
    'media_group_id',
    'status',
    'asset_refs_json',
    'count',
    'deadline_at',
    'last_message_at',
    'closed_by_job_id',
    'created_at',
    'updated_at',
  ],
  [SHEET_NAMES.callbackTokens]: [
    'token',
    'token_set_id',
    'job_id',
    'revision',
    'action',
    'used',
    'superseded',
    'expires_at',
    'issued_at',
    'payload_json',
    'created_at',
    'updated_at',
  ],
  [SHEET_NAMES.idempotencyKeys]: [
    'idem_key',
    'scope',
    'payload_hash',
    'created_at',
    'expires_at',
  ],
  [SHEET_NAMES.publishLocks]: [
    'lock_key',
    'job_id',
    'queue_id',
    'created_at',
    'expires_at',
  ],
  [SHEET_NAMES.jobRuntimeCache]: [
    'job_id',
    'job_type',
    'chat_id',
    'user_id',
    'topic_id',
    'collection_id',
    'active_revision',
    'runtime_status',
    'collage_message_id',
    'assets_message_ids_json',
    'text_message_id',
    'active_callback_set_id',
    'schedule_input_pending',
    'lock_flags_json',
    'preview_payload_json',
    'draft_payload_json',
    'updated_at',
  ],
};

export const SHEET_HEADERS = {
  ...BUSINESS_SHEET_HEADERS,
  ...RUNTIME_SHEET_HEADERS,
};

export const TABLE_COLUMNS = SHEET_HEADERS;

export const DEFAULT_PROMPTS = {
  help_message: [
    'Команды:',
    '/work — обработка фото.',
    '/topic — генерация поста.',
    '/stories — одна картинка-инструкция для сторис.',
    '/slider — карусель из 3-5 слайдов по выбранной теме.',
    '/help — краткая справка по командам.',
    '/start — старт работы и выбор задачи.',
    '',
    'После последнего фото я предложу режим: коллаж или по отдельности.',
  ].join('\n'),
  contact_block: 'Запись по телефону +7 (987) 741-83-99 📞',
  work_album_consistency_extraction: [
    'Проанализируй весь набор фото одной и той же работы и верни короткий locked facts block.',
    'Нужен только список фактов, без вступлений и без лишних объяснений.',
    'Зафиксируй: длину волос, форму укладки, расположение украшения, серьги, одежду, ракурс каждого кадра и что нельзя менять между кадрами.',
    'Если чего-то не видно уверенно, так и напиши: "не видно уверенно".',
  ].join(' '),
  work_image_enhancement_master: [
    'IMAGE EDIT ONLY.',
    'Use only the uploaded real photo as the source.',
    'Preserve the same person, the same face, the same hairstyle result, the same hair length, the same hair color, the same accessories, the same earrings, and the same clothing.',
    'Do not generate a new person or a new hairstyle.',
    'Keep the master’s actual work unchanged and make the image look cleaner, sharper, calmer, and more premium.',
    'Improve exposure, white balance, texture clarity, micro-contrast, and overall polish.',
    'Lightly clean distracting flyaways only when it keeps the real hairstyle shape intact.',
    'Do not crop off the top, volume, curls, decorative details, or key silhouette of the hairstyle.',
    'Keep composition realistic and preserve the environment. You may softly reduce background distraction, but do not replace the background.',
  ].join(' '),
  work_image_enhancement_short: [
    'Make the frame portfolio-ready and visually expensive.',
    'The hairstyle must stay dominant, readable, and realistic.',
  ].join(' '),
  work_image_enhancement_negative: [
    'new person',
    'face swap',
    'different face',
    'different hairstyle',
    'different haircut',
    'different hair length',
    'different hair color',
    'different earrings',
    'different clothing',
    'moved accessory',
    'beauty filter',
    'plastic skin',
    'heavy retouch',
    'new background',
    'cropped hairstyle top',
    'tilted camera',
  ].join(', '),
  work_image_reframe_master: [
    'Reframe the same photo without changing identity or the result of the work.',
    'Keep the camera visually level and the composition calm.',
    'Place the hairstyle in the center of attention and keep the full shape readable.',
    'Preserve the same accessory placement, earrings, clothing, and visible hairstyle details.',
    'Do not invent new hair, new decorations, or a new styling pattern.',
  ].join(' '),
  work_image_polish_master: [
    'Final polish pass for the same real photo only.',
    'The result must look noticeably more premium than the source: cleaner, crisper, richer, and more portfolio-ready.',
    'Preserve the exact same person, haircut, hairstyle shape, hair length, accessory placement, earrings, clothing, and real work result.',
    'Lightly reduce background distraction and tiny messy flyaways only when the real hairstyle silhouette stays exactly the same.',
    'Weak results that look like a simple upscale are not acceptable.',
  ].join(' '),
  work_image_quality_gate: [
    'You are a strict QA evaluator for beauty photo editing.',
    'Compare the original photo and the processed photo.',
    'Check only these criteria: noticeably stronger commercial polish, cleaner texture, clearer shape readability, preserved identity, preserved hairstyle shape, preserved hair length, preserved accessory placement, preserved earrings, preserved clothing.',
    'If the processed result looks too close to the original or drifted from the real work, mark it as retry_needed.',
    'Return strict JSON only:',
    '{"passed":true|false,"retry_needed":true|false,"verdict":"short verdict","issues":["issue1","issue2"]}',
  ].join(' '),
  work_collage_generation: [
    'Create one final vertical portfolio collage from all provided enhanced photos of the same beauty work.',
    'Use only the provided enhanced photos.',
    'Choose a balanced premium composition yourself.',
    'Keep the hairstyle fully readable in every visible fragment and avoid black bars, broken proportions, or cramped crops.',
    'Preserve consistency across the set: same hairstyle shape, same accessory placement, same earrings, same clothing, same identity.',
    'Do not invent new details, text overlays, borders, or decorative frames.',
  ].join(' '),
  work_caption_generation: [
    'Ты пишешь готовые короткие посты для мастера по волосам для публикации в VK.',
    'Пиши от первого лица одного мастера: я, мне, у меня.',
    'Не используй "мы", "наши мастера", "один из мастеров", "команда".',
    'Нужен финальный готовый текст, который можно сразу публиковать.',
    'Не задавай вопросов и не описывай процесс работы модели.',
    'Стиль живой, тёплый и человеческий.',
    'Сделай 1-2 коротких абзаца без воды.',
    'Допустимы 1-3 уместных эмодзи.',
    'Если тип работы виден уверенно, назови его конкретно. Если уверенности нет — не выдумывай услугу.',
    'Не называй работу свадебной, вечерней, мужской, окрашиванием или любой другой конкретной услугой без прямых визуальных признаков.',
    'Не добавляй контактный блок: он подставляется отдельно.',
  ].join(' '),
  topic_post_generation: [
    'Ты пишешь экспертные посты для мастера по волосам.',
    'Тон живой, понятный и тёплый.',
    'Текст конкретный и полезный, без воды и без канцелярита.',
    'Не выдумывай факты и не давай медицинских обещаний.',
    'Контактный блок не добавляй: он подставляется отдельно.',
  ].join(' '),
  topic_image_generation: [
    'Create one clean editorial-style image for an expert hair-care post.',
    'No text on image.',
    'Do not make a portfolio shot of a hairstyle the main subject.',
    'Keep the composition clean, premium, and relevant to the topic.',
  ].join(' '),
};

const WORK_PROMPT_OVERRIDES = {
  work_album_consistency_extraction: [
    'Analyze all photos from one work and return strict locked facts only.',
    'Return plain text sections without markdown and without explanations.',
    'Sections in exact order: IDENTITY_ANCHORS, HAIR_WORK_ANCHORS, ACCESSORY_AND_CLOTHING_ANCHORS, BACKGROUND_POLICY, FORBIDDEN_CHANGES.',
    'Fix immutable anchors: facial geometry, hairline, brow shape, moles/scars, hairstyle length and silhouette, curl pattern, accessory placement, earrings, clothing.',
    'HAIR_WORK_ANCHORS must also lock framing priority: haircut and head should visually dominate the frame and occupy about 75-85% when safe.',
    'BACKGROUND_POLICY must explicitly choose either STRONG_BLUR_REAL_BACKGROUND or NEUTRAL_LIGHT_BACKGROUND and mention that any readable background text must become unreadable.',
    'BACKGROUND_POLICY must also state CAMERA_LEVEL = TRUE and SUBJECT_PRIORITY = HAIRCUT_DOMINANT.',
    'If confidence is low for a field write: not clearly visible.',
  ].join(' '),
  work_image_edit_keep: [
    'IMAGE EDIT ONLY.',
    'Use only the uploaded real photo as source content.',
    'ONE PASS ONLY. Do all relight, cleanup, upscale, framing cleanup, and final premium polish in this single edit.',
    'Primary goal: produce a visibly stronger premium salon portfolio edit, not a weak upscale.',
    'Identity lock is absolute: preserve exact face geometry, side profile, eyes, squint, eyelids, brows, nose shape, ears, beard or stubble, skin marks, asymmetry, earrings, clothing, pose, and neck line.',
    'Hair work lock is absolute: preserve exact haircut and style result, length, silhouette, neckline, fade or graduation, curl pattern, parting, and accessory placement.',
    'Apply strong but realistic enhancement: exposure correction, highlight recovery, shadow lift, soft studio relight, white balance cleanup, texture clarity, crisp upscale, premium micro contrast, and a subtle boost in vibrance.',
    'Keep the real background structure, but make it cleaner and less distracting. Any readable background text must become unreadable. Never regenerate letters or new text.',
    'Framing rule: the haircut is the hero subject. Keep the camera visually level and make the head plus haircut fill roughly 75-85% of the frame whenever safe.',
    'Do not crop or hide key hairstyle shape, top volume, decorative details, neckline shape, or important side profile details.',
    'Negative prompt: new person, face swap, beautified face, different eyes, different squint, different brows, different nose, different ears, different beard, different hairstyle, different haircut, different hair length, different color, different silhouette, different clothing, moved accessory, heavy retouch, readable background text, fake letters, hallucinated diploma text, cropped hairstyle top, lost neckline shape, hidden hairstyle details, tilted camera.',
  ].join(' '),
  work_image_edit_blur: [
    'IMAGE EDIT ONLY.',
    'Use only the uploaded real photo as source content.',
    'ONE PASS ONLY. Do all relight, cleanup, upscale, framing cleanup, and final premium polish in this single edit.',
    'Primary goal: produce a visibly stronger premium salon portfolio edit, not a weak upscale.',
    'Identity lock is absolute: preserve exact face geometry, eyes, nose, lips, jawline, ears, brow shape, hairline, skin marks, asymmetry, earrings, and clothing.',
    'If the face cannot be preserved perfectly, reduce its visual prominence instead of altering it.',
    'Hair work lock is absolute: preserve exact haircut and style result, length, silhouette, curl pattern, parting, and accessory placement.',
    'Apply strong but realistic enhancement: exposure correction, highlight recovery, shadow lift, relight to soft studio look, white balance cleanup, texture clarity, crisp upscale, premium micro contrast, and a subtle boost in vibrance.',
    'Add a slight extra lift in perceived sharpness, exposure, saturation, and hair detail while keeping skin tone and hair color believable.',
    'Framing rule: the haircut is the hero subject. Keep the camera visually level and make the head plus haircut fill roughly 75-85% of the frame whenever safe.',
    'Background rule: keep the real environment only as a very strong blur. The salon interior must not stay detailed. Any certificate, poster, mirror reflection, shelf, window, or readable text must become unreadable and visually secondary.',
    'Readable background text must become unreadable. Never regenerate background text or fake letters.',
    'Do not crop or hide key hairstyle shape, top volume, decorative details, neckline shape, or important side profile details.',
    'Negative prompt: new person, face swap, face beautification, different face geometry, different hairstyle, different haircut, different hair length, different hair color, different curl pattern, different hairline, different earrings, different clothing, moved accessory, beauty filter, plastic skin, heavy retouch, readable background text, fake background letters, hallucinated diploma text, cropped hairstyle top, lost neckline shape, hidden hairstyle details, tilted camera.',
  ].join(' '),
  work_image_edit_neutral: [
    'IMAGE EDIT ONLY.',
    'Use only the uploaded real photo as source content.',
    'ONE PASS ONLY. Do all relight, cleanup, upscale, framing cleanup, and final premium polish in this single edit.',
    'Primary goal: produce a visibly stronger premium salon portfolio edit, not a weak upscale.',
    'Identity lock is absolute: preserve exact face geometry, eyes, nose, lips, jawline, ears, brow shape, hairline, skin marks, asymmetry, earrings, and clothing.',
    'If the face cannot be preserved perfectly, reduce its visual prominence instead of altering it.',
    'Hair work lock is absolute: preserve exact haircut and style result, length, silhouette, curl pattern, parting, and accessory placement.',
    'Apply strong but realistic enhancement: exposure correction, highlight recovery, shadow lift, relight to soft studio look, white balance cleanup, texture clarity, crisp upscale, premium micro contrast, and a subtle boost in vibrance.',
    'Add a slight extra lift in perceived sharpness, exposure, saturation, and hair detail while keeping skin tone and hair color believable.',
    'Framing rule: the haircut is the hero subject. Keep the camera visually level and make the head plus haircut fill roughly 75-85% of the frame whenever safe.',
    'Background rule: replace the busy salon interior with a clean neutral light background. Certificates, posters, mirrors, windows, shelves, clutter, and readable text must disappear into a plain safe background.',
    'Readable background text must become unreadable. Never regenerate background text or fake letters.',
    'Do not crop or hide key hairstyle shape, top volume, decorative details, neckline shape, or important side profile details.',
    'Negative prompt: new person, face swap, face beautification, different face geometry, different hairstyle, different haircut, different hair length, different hair color, different curl pattern, different hairline, different earrings, different clothing, moved accessory, beauty filter, plastic skin, heavy retouch, readable background text, fake background letters, hallucinated diploma text, cropped hairstyle top, lost neckline shape, hidden hairstyle details, tilted camera.',
  ].join(' '),
  work_brow_consistency_extraction: [
    'Analyze all uploaded eyebrow photos from the same work and return strict locked facts only.',
    'Return plain text sections without markdown and without explanations.',
    'Sections in exact order: IDENTITY_ANCHORS, BROW_WORK_ANCHORS, ACCESSORY_AND_CLOTHING_ANCHORS, BACKGROUND_POLICY, FORBIDDEN_CHANGES.',
    'Lock exact face geometry, eye shape, squint, eyelids, brow bone, visible skin marks, asymmetry, hairline, earrings, clothing, and visible pose.',
    'BROW_WORK_ANCHORS must lock exact natural eyebrow shape, arch, thickness, tail direction, spacing, and visible permanent makeup result when present.',
    'BROW_WORK_ANCHORS must also state FRAMING_PRIORITY = BROWS_CLOSE_UP.',
    'BACKGROUND_POLICY must explicitly choose either STRONG_BLUR_REAL_BACKGROUND or NEUTRAL_LIGHT_BACKGROUND and require unreadable background text.',
    'BACKGROUND_POLICY must also state CAMERA_LEVEL = TRUE and SUBJECT_PRIORITY = BROWS_DOMINANT.',
    'If confidence is low for a field write: not clearly visible.',
  ].join(' '),
  work_brow_edit_keep: [
    'IMAGE EDIT ONLY.',
    'Use only the uploaded real eyebrow photo as source content.',
    'ONE PASS ONLY. Do all relight, cleanup, upscale, close-up framing cleanup, and final premium polish in this single edit.',
    'Primary goal: produce a premium portfolio eyebrow edit while preserving the exact real person and real eyebrow geometry.',
    'Identity lock is absolute: preserve exact face geometry, side profile, eyes, squint, eyelids, brow bone, nose, ears, beard or stubble, skin marks, asymmetry, clothing, and pose.',
    'Eyebrow lock is absolute: preserve exact eyebrow placement, arch, width, tail direction, spacing, and visible hair pattern unless the chosen brow mode explicitly asks for a before-state simulation.',
    'Keep the camera visually level and crop naturally so one eyebrow or both eyebrows with the eyes become the hero subject and occupy roughly 75-85 percent of the frame when safe.',
    'Apply strong but realistic relight, texture clarity, crisp upscale, premium micro contrast, and subtle vibrance.',
    'Keep the real background structure, but make it cleaner and less distracting. Any readable background text must become unreadable. Never regenerate letters or new text.',
    'Negative prompt: new person, face swap, beautified face, different eyes, different squint, different brows, different arch, different brow spacing, different nose, different ears, different beard, different clothing, readable background text, fake letters, hallucinated diploma text, plastic skin, tilted camera.',
  ].join(' '),
  work_brow_edit_blur: [
    'IMAGE EDIT ONLY.',
    'Use only the uploaded real eyebrow photo as source content.',
    'ONE PASS ONLY. Do all relight, cleanup, upscale, close-up framing cleanup, and final premium polish in this single edit.',
    'Primary goal: produce a premium portfolio eyebrow edit while preserving the exact real person and real eyebrow geometry.',
    'Identity lock is absolute: preserve exact face geometry, side profile, eyes, squint, eyelids, brow bone, nose, ears, beard or stubble, skin marks, asymmetry, clothing, and pose.',
    'Eyebrow lock is absolute: preserve exact eyebrow placement, arch, width, tail direction, spacing, and visible hair pattern unless the chosen brow mode explicitly asks for a before-state simulation.',
    'Keep the camera visually level and crop naturally so one eyebrow or both eyebrows with the eyes become the hero subject and occupy roughly 75-85 percent of the frame when safe.',
    'Apply strong but realistic relight, texture clarity, crisp upscale, premium micro contrast, and subtle vibrance.',
    'Keep the real background only as a very strong blur. Any certificate, poster, mirror reflection, shelf, window, or readable text must become unreadable and visually secondary.',
    'Negative prompt: new person, face swap, beautified face, different eyes, different squint, different brows, different arch, different brow spacing, different nose, different ears, different beard, different clothing, readable background text, fake letters, hallucinated diploma text, plastic skin, tilted camera.',
  ].join(' '),
  work_brow_edit_neutral: [
    'IMAGE EDIT ONLY.',
    'Use only the uploaded real eyebrow photo as source content.',
    'ONE PASS ONLY. Do all relight, cleanup, upscale, close-up framing cleanup, and final premium polish in this single edit.',
    'Primary goal: produce a premium portfolio eyebrow edit while preserving the exact real person and real eyebrow geometry.',
    'Identity lock is absolute: preserve exact face geometry, side profile, eyes, squint, eyelids, brow bone, nose, ears, beard or stubble, skin marks, asymmetry, clothing, and pose.',
    'Eyebrow lock is absolute: preserve exact eyebrow placement, arch, width, tail direction, spacing, and visible hair pattern unless the chosen brow mode explicitly asks for a before-state simulation.',
    'Keep the camera visually level and crop naturally so one eyebrow or both eyebrows with the eyes become the hero subject and occupy roughly 75-85 percent of the frame when safe.',
    'Apply strong but realistic relight, texture clarity, crisp upscale, premium micro contrast, and subtle vibrance.',
    'Replace the busy salon background with a clean neutral light studio background. Certificates, posters, mirrors, windows, shelves, clutter, and readable text must disappear into a plain safe background.',
    'Negative prompt: new person, face swap, beautified face, different eyes, different squint, different brows, different arch, different brow spacing, different nose, different ears, different beard, different clothing, readable background text, fake letters, hallucinated diploma text, plastic skin, tilted camera.',
  ].join(' '),
  work_image_enhancement_negative: [
    'new person',
    'face swap',
    'face beautification',
    'different face geometry',
    'different hairstyle',
    'different haircut',
    'different hair length',
    'different hair color',
    'different curl pattern',
    'different hairline',
    'different earrings',
    'different clothing',
    'moved accessory',
    'beauty filter',
    'plastic skin',
    'heavy retouch',
    'readable background text',
    'fake background letters',
    'hallucinated diploma text',
    'cropped hairstyle top',
    'lost neckline shape',
    'hidden hairstyle details',
    'tilted camera',
  ].join(', '),
  work_collage_generation: [
    'Create one final vertical portfolio collage from all provided enhanced photos of the same beauty work.',
    'Use only the provided enhanced photos.',
    'All provided assets are mandatory: do not drop any photo and do not duplicate any photo.',
    'Choose a balanced premium composition that keeps hairstyle readable in every panel and avoids black bars or broken proportions.',
    'Preserve consistency: same identity, hairstyle shape, accessory placement, earrings, clothing.',
    'Keep background treatment safe and keep any background text unreadable.',
    'Do not invent details, text overlays, borders, or decorative frames.',
  ].join(' '),
  work_brow_collage_generation: [
    'Create one final vertical portfolio collage from all provided enhanced eyebrow photos of the same work.',
    'Use only the provided enhanced photos.',
    'All provided assets are mandatory: do not drop any photo and do not duplicate any photo.',
    'Keep eyebrows and eye area clearly readable in every panel. Avoid black bars, broken proportions, or tiny unreadable crops.',
    'Preserve consistency: same identity, same eyebrow shape logic, same clothing, same visible side profile.',
    'Keep background treatment safe and keep any background text unreadable.',
    'Do not invent details, text overlays, borders, or decorative frames.',
  ].join(' '),
  work_brow_caption_generation: [
    'Напиши короткий живой пост для мастера по бровям.',
    'Это финальный текст для публикации, а не описание процесса.',
    'Пиши от первого лица одного мастера, без мы и без команды.',
    'Сделай 1-2 коротких абзаца с тёплой человеческой подачей.',
    'Если по фото явно видно, что это перманентный макияж или оформление бровей, можешь назвать это прямо.',
    'Не добавляй контактный блок — он добавляется отдельно.',
  ].join(' '),
};

Object.assign(DEFAULT_PROMPTS, WORK_PROMPT_OVERRIDES);
Object.assign(DEFAULT_PROMPTS, {
  work_caption_generation: [
    'Ты пишешь готовые короткие посты для мастера по волосам для публикации в VK.',
    'Пиши от первого лица одного мастера: я, мне, у меня.',
    'Не используй "мы", "наши мастера", "один из мастеров", "команда".',
    'Нужен финальный готовый текст, который можно сразу публиковать.',
    'Не задавай вопросов и не описывай процесс работы модели.',
    'Стиль живой, тёплый и человеческий.',
    'Делай текст короче и разнообразнее по длине: иногда достаточно 2 коротких строк, иногда 1-2 коротких абзацев.',
    'Главный акцент делай на результате для клиента: что получилось, как выглядит форма, текстура, силуэт, аккуратность и удобство в носке.',
    'Не повторяй в каждом посте формулировки про то, что мне это нравится или я это люблю. Такие фразы допустимы редко и только когда действительно к месту.',
    'Если тип работы виден уверенно, назови его конкретно. Если уверенности нет — не выдумывай услугу.',
    'Не называй работу свадебной, вечерней, мужской, окрашиванием или любой другой конкретной услугой без прямых визуальных признаков.',
    'Допустимы 0-2 уместных эмодзи.',
    'Контактный блок не добавляй: он подставляется отдельно.',
  ].join(' '),
  work_brow_caption_generation: [
    'Напиши короткий живой пост для мастера по бровям.',
    'Это финальный текст для публикации, а не описание процесса.',
    'Пиши от первого лица одного мастера, без мы и без команды.',
    'Делай текст короче и разнообразнее по длине: иногда достаточно 2 коротких строк, иногда 1-2 коротких абзацев.',
    'Главный акцент делай на результате для клиента: форма, аккуратность, мягкость или насыщенность результата, общий вид взгляда.',
    'Не повторяй в каждом посте формулировки про то, что мне это нравится или я это люблю. Такие фразы допустимы редко и только когда действительно к месту.',
    'Если по фото явно видно, что это перманентный макияж или оформление бровей, можешь назвать это прямо.',
    'Допустимы 0-2 уместных эмодзи.',
    'Не добавляй контактный блок — он добавляется отдельно.',
  ].join(' '),
});

export const CALLBACK_ACTIONS = [
  'work_photo_type_normal',
  'work_photo_type_studio',
  'work_subject_hair',
  'work_subject_brows',
  'work_prompt_mode_normal',
  'work_prompt_mode_test',
  'brow_output_before_after',
  'brow_output_after_only',
  'render_mode_collage',
  'render_mode_separate',
  'background_mode_keep',
  'background_mode_blur',
  'background_mode_neutral',
  'cleanup_on',
  'cleanup_off',
  'version_prev',
  'version_next',
  'regenerate_images',
  'regenerate_text',
  'regenerate_all',
  'publish_confirm',
  'cancel',
];

DEFAULT_PROMPTS.topic_post_generation = [
  'Ты пишешь короткие профессиональные посты для мастера по волосам.',
  'Это не подпись к фото работы и не портфолио-пост, а отдельный полезный пост для клиентов.',
  'Пиши так, как будто мастер по-дружески говорит с клиентом вживую.',
  'Пиши только от первого лица одного мастера: я, мне, у меня. Не используй мы, наш салон, наши мастера, команда.',
  'Используй только тему и контекст из title, brief, tags.',
  'Текст должен быть коротким, простым, очень живым и дружелюбным.',
  'Избегай профессионального жаргона и сложных терминов, если без них можно обойтись.',
  'Если без термина не обойтись, сразу объясняй его простыми словами внутри текста.',
  'Если упоминаешь несмываемый уход, сразу называй бытовые примеры: спрей, крем, лосьон или флюид.',
  'Не называй волосы словом "длина", если речь просто о волосах. Говори "волосы".',
  'Не называй расчёску словом "щётка", если речь о обычном домашнем расчёсывании. Говори "расчёска", если не нужен более точный инструмент.',
  'Держи объем примерно 450-750 знаков до финального контактного блока.',
  'Начинай с короткого теплого вступления в духе "Добрый день, дорогие, сегодня решила поделиться..." но не копируй одну и ту же формулу каждый раз.',
  'Вступление должно меняться от поста к посту, но оставаться тёплым, личным и естественным.',
  'Допустимы 1-3 уместных эмодзи, если они делают текст живее.',
  'Без канцелярита, без лекционного тона, без медицинских обещаний, без рекламного пафоса и без нейросеточной гладкости.',
  'Не используй кавычки и длинные тире, если без них можно обойтись. Предпочитай простую пунктуацию.',
  'Если в теме есть ошибки, шаги, правила или советы, оформляй их списком: каждая мысль с новой строки.',
  'Если используешь список, каждый пункт начинай с маркера "- ".',
  'Не пиши перечисления в одну строку через двоеточие и точку с запятой.',
  'Каждый пункт списка должен быть коротким: 1 простая мысль или 1-2 короткие фразы.',
  'Обычно дай 1 короткий вводный абзац и затем список из 2-4 пунктов. Если список не нужен, оставь 2-3 коротких абзаца.',
  'Не ставь подзаголовок перед списком.',
  'Не добавляй финальный абзац ради финального абзаца. Завершай только если это добавляет смысл.',
  'Нужна короткая дружелюбная концовка в живом тоне. Номер телефона не пиши сам: он подставляется отдельно.',
  'Не выдумывай факты и не привязывай текст к конкретной фотографии результата.',
  'Не превращай текст в длинную статью, лекцию, буклет или описание готовой прически.',
  'Отдай готовый финальный текст поста без служебных комментариев.',
].join(' ');

DEFAULT_PROMPTS.topic_image_generation = [
  'Create one realistic smartphone photo for a professional hair master post.',
  'Use the attached salon reference images as interior anchors.',
  'The scene should feel like it was photographed on an iPhone in this exact small salon, not in a similar salon and not in a perfect studio.',
  'Keep the interior almost unchanged from the references: light textured walls, black-and-white checkered floor, black salon chairs, mirrors, simple work surfaces, shelves, tidy lived-in atmosphere.',
  'Do not redesign the room, do not invent different architecture, and do not swap furniture style.',
  'The safest variation is to keep the same room and only change the camera angle, the crop, the distance, or the object of focus.',
  'If the topic needs a subject detail, make a closer shot inside the same salon instead of creating a different location.',
  'Treat seasonal decor, certificates, posters, tinsel, and random small objects as incidental details. Do not repeat them unless the topic truly needs them.',
  'This is not a portfolio image of a finished hairstyle, not a before-after image, and not an ad banner.',
  'The image must support an expert client-facing topic about hair care, routine, common mistakes, protection, or maintaining the result between salon visits.',
  'Use the topic context from title, brief, and tags to choose a relevant subject.',
  'Allowed main subjects: care products, styling and care tools, working corner, hands of a master in a neutral process detail, towel, brush, comb, bottle, diffuser, thermal protection context, calm salon routine.',
  'Hair may appear only as secondary context. Do not make a finished hairstyle, haircut, coloring result, or client portrait the main hero of the image.',
  'Prefer normal phone-camera perspective, natural light behavior, slight бытовая imperfectness, real textures, and believable detail.',
  'No text on image, no infographic look, no collage, no fake social media UI, no glossy ad look, and no uncanny generated perfection.',
  'No hero hairstyle, no portfolio shot, no before-after, no price card, no heavy retouch, no luxury showroom feel, and no exaggerated fashion editorial drama.',
].join(' ');

DEFAULT_PROMPTS.story_manifest_generation = [
  'Ты создаёшь короткий JSON manifest для stories про уход за волосами.',
  'Верни только валидный JSON для одного вертикального слайда.',
  'Используй ровно такую форму: {"eyebrow":"","title":"...","body":"...","bullets":["..."],"footer":"..."}.',
  'Тон должен быть таким же, как у профессиональных постов мастера по волосам и у коротких постов /work: живой, тёплый, человеческий.',
  'Пиши только от первого лица одного мастера: я, мне, у меня. Не используй мы, наш салон, наши мастера, команда.',
  'Подача должна звучать как короткий живой фрагмент речи мастера, а не как памятка, статья, инфографика или редакторский текст.',
  'Предпочитай простой разговорный русский, короткие естественные фразы и практичные формулировки.',
  'Разрешены естественные разговорные заходы вроде: "Если коротко,", "Часто слышу этот вопрос.", "Я обычно советую...", "По опыту скажу так:". Меняй формулировку, не повторяй один и тот же заход каждый раз.',
  'Заголовок должен ясно называть тему и звучать по-человечески.',
    'body должен коротко раскрывать тему и сразу давать суть ответа, а не просто повторять заголовок.',
    'Не повторяй заголовок в body другими словами и не начинай body с той же самой формулировки, что уже стоит в title.',
  'Если тема вопросительная, в body должен быть прямой человеческий ответ в 1-2 коротких предложениях.',
  'Не пиши абстрактно. Вместо общих слов вроде "домашний уход", "увлажнение", "баланс" без действия давай простой понятный совет.',
  'Избегай профессионального жаргона и сложных слов. Лучше писать "кожный жир", чем "себум", и "внешний слой волоса", чем "кутикула", если это не ухудшает смысл.',
    'Если без специального слова не обойтись, не объясняй его внутри body или bullets.',
  'Если вместо общего "несмываемый уход" можно сразу назвать конкретно, пиши проще: спрей, крем, лосьон или флюид.',
  'Не называй волосы словом "длина", если речь просто о волосах. Лучше "волосы".',
  'Не называй расчёску словом "щётка", если не нужен именно такой точный инструмент.',
  'bullets - это 2-4 коротких совета или правила по делу.',
    'Каждый bullet начинай с большой буквы.',
    'Не пиши bullets в Title Case. С заглавной буквы должно быть только первое слово и имена собственные, а не каждое слово.',
  'Каждый bullet должен звучать как конкретный совет от мастера в обычной речи. Лучше "После каждого мытья оставляйте кондиционер по длине", чем "Кондиционер для мягкости".',
    'Если используешь неочевидный термин вроде "себум", не объясняй его в body или bullets. Любое пояснение таких слов пиши только в footer простым языком. Если терминов несколько, footer делай многострочным: одно пояснение на одной строке.',
  'Избегай пустых общих фраз. Каждый body и каждый bullet должны нести реальную пользу.',
  'Не звучать продажно, официально, лекционно, канцелярски или слишком вылизанно.',
  'Не выводи теги, keywords, строки через точку с запятой, placeholders и фразы вроде тема про.',
  'eyebrow по умолчанию оставляй пустым, если для него нет явной пользы.',
  'Не добавляй markdown, пояснения или комментарии вне JSON.',
  ].join(' ');

DEFAULT_PROMPTS.story_visual_generation = [
  'Create one realistic vertical story visual for a hair-care topic.',
  'The image should feel like a simple mobile-friendly social post, not a polished ad.',
  'Use one clean subject, calm composition, and empty space for overlays.',
  'When color accents are useful, prefer the salon brand palette with main colors #CE6BD6 and #A21A92.',
  'Use these colors as restrained primary accents in objects, packaging details, props, reflections, or soft background elements instead of random accent colors.',
  'The image itself must contain zero readable text: no letters, no words, no numbers, no labels, no captions, no UI, no posters, no logos, no watermarks, and no packaging text.',
  'Do not create an infographic, a collage, a grid, a multi-panel layout, a quote card, or a text card. Generate a single plain background image only.',
  'Prefer unlabeled objects, plain surfaces, and simple scenes that stay useful with no blur or only light blur and a dark overlay.',
  'No portrait hero shot, no glossy studio finish, and no typography baked into the image.',
].join(' ');

DEFAULT_PROMPTS.creative_manifest_generation = [
  'Ты создаёшь короткий JSON manifest для одной цепляющей creative-карточки про волосы, клиентов и салонную жизнь.',
  'Верни только валидный JSON для одного вертикального слайда.',
  'Используй ровно такую форму: {"eyebrow":"","headline":"...","subhead":"...","bullets":["..."],"footer":""}.',
  'headline — это один сильный hook: короткая, смешная, узнаваемая или цепляющая фраза, которую легко прочитать за секунду на телефоне.',
  'subhead — это одна короткая живая строка, которая добивает шутку или добавляет узнаваемую деталь. Не повторяй headline другими словами и не начинай subhead с тех же слов.',
  'Не пиши служебные фразы вроде "ироничный креатив про...", "тема про...", "шутка про..." или "креатив о...".',
  'Тон лёгкий, умный, salon-coded и человеческий. Разрешены клиентские фразы, салонный тайминг, инструменты и средства как персонажи, бытовые боли клиентов, лёгкая самоирония мастера.',
  'Юмор должен быть добрым и узнаваемым. Не используй токсичный сарказм, стыжение клиента, грубость или длинный сетап.',
  'Избегай плотного объяснения. Никаких длинных абзацев и сложного сторителлинга.',
  'bullets по умолчанию оставляй пустым массивом. Добавляй максимум 1-2 коротких bullet только если они реально усиливают шутку или ритм карточки.',
  'Если bullets есть, каждый пункт начинай с большой буквы и не пиши их в Title Case.',
  'Избегай профессионального жаргона и сложных терминов. Если термин всё же нужен, не объясняй его в headline, subhead или bullets: короткое пояснение можно дать только в footer.',
  'Если вместо общего "несмываемый уход" можно сразу назвать конкретно, пиши проще: спрей, крем, лосьон или флюид.',
  'Не называй волосы словом "длина", если речь просто о волосах. Не называй расчёску словом "щётка", если не нужен именно такой точный инструмент.',
  'Не добавляй markdown или комментарии вне JSON.',
].join(' ');

DEFAULT_PROMPTS.creative_visual_generation = [
  'Create one vertical creative visual for a playful haircare post.',
  'Prefer simple flat vector or light illustration style with restrained shapes and cleaner composition rather than loud poster energy.',
  'When color accents are useful, prefer the salon brand palette with main colors #CE6BD6 and #A21A92.',
  'Let these two colors drive the main accent logic instead of random bright hues, while keeping the overall image simple and readable.',
  'Prefer object-first composition rather than people.',
  'Keep it visually simple and readable so the overlay text can sit on top without heavy darkening.',
  'The image itself must contain zero readable text: no letters, no words, no numbers, no labels, no captions, no UI, no speech bubbles with text, no logos, and no watermarks.',
  'Do not create a meme card, poster, infographic, collage, grid, or any composition that already contains written content. Generate a text-free background image only.',
  'Prefer one strong visual idea with objects, symbols, or abstract hair-industry cues, but without typography.',
  'Avoid neon overload, harsh contrast, and noisy decorative clutter.',
  'No portrait hero, no hairstyle portfolio shot, no ad banner, and no text baked into the image.',
].join(' ');

DEFAULT_PROMPTS.slider_manifest_generation = [
  'Ты создаёшь короткий JSON manifest для слайдера про уход за волосами на 3-5 слайдов.',
  'Верни только валидный JSON.',
  'Используй ровно такую форму: {"eyebrow":"","coverTitle":"...","coverSubtitle":"...","coverBullets":["..."],"slides":[{"eyebrow":"","title":"...","body":"...","bullets":["..."],"footer":""}],"footer":""}.',
  'coverSubtitle должен коротко объяснять суть темы, а не повторять brief и не звучать как "небольшая карусель о...".',
  'Для тем формата "база ухода", "набор средств" или "что нужно дома" coverBullets должны перечислять весь фактический набор, который потом раскрывается на следующих карточках.',
  'Если дальше на слайдах есть шампунь, кондиционер, маска и несмываемый уход, на обложке должны быть именно эти пункты, а не общая фраза.',
    'Каждый контентный слайд должен содержать меньше текста, чем stories, но не быть пустым: 1 короткий title, 1 законченный полезный body и при необходимости 1-2 коротких bullets по делу.',
    'Не повторяй title в body. body должен продолжать мысль, а не перефразировать заголовок.',
  'Избегай профессионального жаргона и сложных терминов. Лучше писать просто и понятно, как мастер объясняет клиенту без лишних слов.',
    'Если термин всё же нужен, не объясняй его внутри body или bullets.',
  'Если вместо общего "несмываемый уход" можно сразу назвать конкретно, пиши проще: спрей, крем, лосьон или флюид.',
  'Не называй волосы словом "длина", если речь просто о волосах.',
  'Не называй расчёску словом "щётка", если не нужен именно такой точный инструмент.',
    'Каждый bullet начинай с большой буквы.',
    'Не пиши bullets в Title Case. С заглавной буквы должно быть только первое слово и имена собственные, а не каждое слово.',
    'Если используешь неочевидный термин вроде "себум", не объясняй его в body или bullets. Любое пояснение таких слов пиши только в footer простым языком. Если терминов несколько, footer делай многострочным: одно пояснение на одной строке.',
  'Не растягивай мысли. Один слайд — одна понятная мысль.',
  'Пиши по-человечески, просто и полезно, как мастер коротко объясняет клиенту.',
  'Не выводи теги, keywords, placeholders, "тема про", "карусель про" и другие служебные фразы.',
  'eyebrow на обложке по умолчанию оставляй пустым.',
  'Не добавляй markdown или комментарии вне JSON.',
].join(' ');

DEFAULT_PROMPTS.slider_visual_generation = [
  'Create vertical slide visuals for a practical hair-care guide.',
  'Design them to work as a compact carousel with clear safe space for overlay text.',
  'When color accents are useful, prefer the salon brand palette with main colors #CE6BD6 and #A21A92.',
  'Use these colors as restrained accent anchors in props, packaging hints, surfaces, or abstract details instead of random accent colors.',
  'Prefer realistic, simple, object-first compositions over portrait shots.',
  'The image itself must contain zero readable text: no letters, no words, no numbers, no labels, no posters, no logos, no watermarks, and no UI.',
  'Do not generate a collage, a tiled grid, a checklist card, a quote card, or any slide that already contains written instructions. Generate one plain text-free background image only.',
  'Prefer blank or unlabeled tools, clean materials, neutral hands, and calm surfaces that still look good after strong blur and dark overlay.',
  'No collage frame, no luxury ad polish, and no hairstyle hero image.',
].join(' ');

DEFAULT_PROMPTS.topic_image_generation = [
  'Create one realistic smartphone photo for a professional hair master post.',
  'Use the attached salon reference images as interior anchors.',
  'The scene should feel like it was photographed on an iPhone in this exact small salon, not in a similar salon and not in a perfect studio.',
  'Keep the interior almost unchanged from the references: light textured walls, black-and-white checkered floor, black salon chairs, mirrors, simple work surfaces, shelves, tidy lived-in atmosphere.',
  'When color accents are useful, prefer the salon brand palette with main colors #CE6BD6 and #A21A92.',
  'Use these colors carefully in products, towels, accessories, reflections, or subtle decor accents instead of introducing random accent colors.',
  'Do not redesign the room, do not invent different architecture, and do not swap furniture style.',
  'The safest variation is to keep the same room and only change the camera angle, the crop, the distance, or the object of focus.',
  'If the topic needs a subject detail, make a closer shot inside the same salon instead of creating a different location.',
  'Treat seasonal decor, certificates, posters, tinsel, and random small objects as incidental details. Do not repeat them unless the topic truly needs them.',
  'This is not a portfolio image of a finished hairstyle, not a before-after image, and not an ad banner.',
  'The image must support an expert client-facing topic about hair care, routine, common mistakes, protection, or maintaining the result between salon visits.',
  'Use the topic context from title, brief, and tags to choose a relevant subject.',
  'Allowed main subjects: care products, styling and care tools, working corner, hands of a master in a neutral process detail, towel, brush, comb, bottle, diffuser, thermal protection context, calm salon routine.',
  'Hair may appear only as secondary context. Do not make a finished hairstyle, haircut, coloring result, or client portrait the main hero of the image.',
  'The image itself must contain zero readable text: no letters, no words, no numbers, no labels, no captions, no signage, no UI, no logos, and no watermarks.',
  'Do not generate an infographic, a tiled collage, a checklist card, a quote card, a poster, or any multi-panel composition. Generate one plain realistic photo only.',
  'If an object normally has a label, keep it blank, turned away, or too soft to read.',
  'Prefer normal phone-camera perspective, natural light behavior, slight everyday imperfectness, real textures, and believable detail.',
  'No text on image, no infographic look, no collage, no fake social media UI, no glossy ad look, and no uncanny generated perfection.',
  'No hero hairstyle, no portfolio shot, no before-after, no price card, no heavy retouch, no luxury showroom feel, and no exaggerated fashion editorial drama.',
].join(' ');

export const WORK_SESSION_TTL_MINUTES = 10;
export const WORK_COLLECTION_DEBOUNCE_SECONDS = 3;
export const WORK_COLLECTION_INITIAL_ALBUM_GRACE_SECONDS = 4;
export const WORK_COLLECTION_PARTIAL_ALBUM_GRACE_SECONDS = 6;
export const CALLBACK_TTL_MINUTES = 120;
export const TOPIC_RESERVATION_MINUTES = 120;

export const USER_MESSAGES = {
  fallbackCaption: 'Готово.',
  genericError: 'Не получилось закончить действие. Попробуй ещё раз.',
  unknownCommand: 'Не поняла команду. Нажми /help.',
  workWindowOpened: 'Окно для фото открыто.',
  workStarted: 'Выбери, что обработать.',
  workPhotoTypeChoice: 'Какое фото обработать?',
  workPhotoTypeChoiceHint: 'Обычное или студийное. Студийное = светлый студийный фон.',
  workSubjectChoice: 'Что обработать?',
  workSubjectChoiceHint: 'Прически / стрижки или брови.',
  workPromptModeChoice: 'Выбери режим.',
  workPromptModeHint: 'Обычный или тестовый.',
  workPhotoRequest: `Отправь 1-3 фото одной работы одним альбомом. Сессия активна ${WORK_SESSION_TTL_MINUTES} минут.`,
  workBrowOutputChoice: 'Как показать брови?',
  workBrowOutputChoiceHint: 'До / после или только после.',
  workModeChoice: 'Как показать результат?',
  workModeChoiceHint: 'Выбери режим ниже.',
  workBackgroundChoice: 'Какой фон сделать?',
  workBackgroundChoiceHint: 'Выбери вариант ниже.',
  workCleanupChoice: 'Почистить фон?',
  workCleanupChoiceHint: 'Убрать мелкий визуальный мусор.',
  noReadyTopic: 'Сейчас нет готовых тем.',
  workBeforePhoto: 'Сначала отправь /work, потом фото.',
  topicTaken: 'Тему взяла. Готовлю материал.',
  topicGeneratingText: 'Пишу текст.',
  topicGeneratingImages: 'Готовлю картинку.',
  assemblingPreview: 'Собираю результат.',
  workProcessingStarted: 'Начинаю обработку.',
  workAnalyzingPhotos: 'Анализирую фото.',
  workEnhancingImages: 'Обрабатываю фото.',
  workPreparingText: 'Пишу текст.',
  workReady: 'Готово.',
  callbackStale: 'Эта кнопка уже неактуальна.',
  callbackUseLatestPreview: 'Это старая версия кнопок. Используй последнюю.',
  callbackUnknown: 'Не поняла действие.',
  draftCancelled: 'Черновик отменён.',
  versionChanged: 'Показываю другую версию.',
  separatePreviewReady: 'Готово. Ниже отправила текущую версию альбомом.',
  generationQueued: {
    collage: 'Начинаю обработку. Соберу коллаж.',
    separate: 'Начинаю обработку. Подготовлю фото по отдельности.',
  },
  actionMessages: {
    work_photo_type_normal: '',
    work_photo_type_studio: '',
    work_subject_hair: '',
    work_subject_brows: '',
    work_prompt_mode_normal: '',
    work_prompt_mode_test: '',
    brow_output_before_after: '',
    brow_output_after_only: '',
    render_mode_collage: '',
    render_mode_separate: '',
    background_mode_keep: '',
    background_mode_blur: '',
    background_mode_neutral: '',
    cleanup_on: '',
    cleanup_off: '',
    version_prev: '',
    version_next: '',
    regenerate_images: 'Готовлю новые изображения.',
    regenerate_text: 'Пишу новый текст.',
    regenerate_all: 'Пересобираю всё.',
    publish_confirm: '',
    cancel: 'Черновик отменён.',
  },
  actionCallbackAnswers: {
    work_photo_type_normal: 'Выбран тип фото: обычное.',
    work_photo_type_studio: 'Выбран тип фото: студийное.',
    work_subject_hair: 'Выбран режим: прически / стрижки.',
    work_subject_brows: 'Выбран режим: брови.',
    work_prompt_mode_normal: 'Выбран обычный режим.',
    work_prompt_mode_test: 'Выбран тестовый режим.',
    brow_output_before_after: 'Выбран режим: до / после.',
    brow_output_after_only: 'Выбран режим: только после.',
    render_mode_collage: 'Выбран режим: коллаж.',
    render_mode_separate: 'Выбран режим: по отдельности.',
    background_mode_keep: 'Выбран фон: как есть.',
    background_mode_blur: 'Выбран фон: сильный блюр.',
    background_mode_neutral: 'Выбран фон: светлый студийный.',
    cleanup_on: 'Почистить фон: да.',
    cleanup_off: 'Почистить фон: нет.',
    version_prev: 'Открываю предыдущую версию.',
    version_next: 'Открываю следующую версию.',
    regenerate_images: 'Запускаю новую генерацию изображений.',
    regenerate_text: 'Запускаю новую генерацию текста.',
    regenerate_all: 'Запускаю полную пересборку.',
    publish_confirm: 'Отмечаю как опубликованное.',
    cancel: 'Черновик отменён.',
  },
  progressPhotoAccepted(count) {
    return `Фото принято: ${count}/3.`;
  },
};
